openapi: "3.0.2"
info:
  title: Book Shelf API
  version: "1.0"
servers:
  - url: https://localhost:3000/v1
paths:
  /books:
    get:
      responses:
        "200":
          description: OK
    post:
      responses:
        "200":
          description: OK
  /books/{id}:
    get:
      responses:
        "200":
          description: OK
    patch:
      responses:
        "200":
          description: OK
    delete:
      responses:
        "200":
          description: OK
